import {
  LoadListing,
  Order,
  DriverProfile,
  SupplierProfile,
  ReturnLoad,
  NotificationItem,
} from '../types/lorrio';

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: '🚛 Lorry Dispatched (Order #LR1024)',
    message: 'Driver Sujith V. has departed Mayyil Quarry in Kannur. Estimated arrival at Kalpetta site: 04:30 PM.',
    timestamp: '10 mins ago',
    read: false,
    type: 'ORDER',
    forRole: 'CUSTOMER',
  },
  {
    id: 'NOTIF-02',
    title: '🪨 New Return Load Available',
    message: 'High-payout return trip available from Kalpetta Crusher Unit to Kannur (+₹5,400).',
    timestamp: '25 mins ago',
    read: false,
    type: 'DRIVER',
    forRole: 'DRIVER',
  },
  {
    id: 'NOTIF-03',
    title: '✓ Quarry Verified',
    message: 'Mayyil Quarry permit verified for Kannur-Wayanad laterite stone dispatch.',
    timestamp: '2 hours ago',
    read: true,
    type: 'SYSTEM',
    forRole: 'ALL',
  },
];

export const INITIAL_LOADS: LoadListing[] = [
  {
    id: 'LOAD-KN-01',
    supplierId: 'SUP-01',
    supplierName: 'Mayyil Laterite Quarry',
    supplierPhone: '+91 98471 22341',
    supplierRating: 4.9,
    isVerifiedSupplier: true,
    material: 'Laterite Stone',
    quality: 'Premium Cut Finish (High Strength)',
    quantity: 500,
    unit: 'stones',
    pickupLocation: 'Mayyil Quarry, Kannur',
    pickupCoords: { address: 'Mayyil Quarry, Kannur District, Kerala', lat: 11.9744, lng: 75.4851 },
    destinationLocation: 'Kalpetta Town, Wayanad',
    destinationCoords: { address: 'Plot 42, Main Road, Kalpetta, Wayanad', lat: 11.6094, lng: 76.0827 },
    materialPrice: 16500,
    transportPrice: 6500,
    platformFee: 500,
    totalPrice: 23500,
    vehicleType: '10-Wheel Lorry (16 Ton)',
    availableDate: 'Tomorrow, 07:00 AM',
    status: 'AVAILABLE',
    driverId: 'DRV-01',
    driverName: 'Sujith V. (Express Haulers)',
    driverPhone: '+91 94473 88102',
    driverRating: 4.85,
    vehicleNumber: 'KL-13-AF-4921',
    isVerifiedDriver: true,
  },
  {
    id: 'LOAD-KN-02',
    supplierId: 'SUP-02',
    supplierName: 'Sreekandapuram Stone Works',
    supplierPhone: '+91 97450 11923',
    supplierRating: 4.7,
    isVerifiedSupplier: true,
    material: 'Laterite Stone',
    quality: 'Standard Machine Cut (Building Grade)',
    quantity: 500,
    unit: 'stones',
    pickupLocation: 'Sreekandapuram, Kannur',
    pickupCoords: { address: 'Sreekandapuram Stone Works, Kannur', lat: 12.0305, lng: 75.5262 },
    destinationLocation: 'Mananthavady, Wayanad',
    destinationCoords: { address: 'Mananthavady Site, Wayanad', lat: 11.8026, lng: 76.0034 },
    materialPrice: 15000,
    transportPrice: 6200,
    platformFee: 450,
    totalPrice: 21650,
    vehicleType: '6-Wheel Lorry (10 Ton)',
    availableDate: 'Tomorrow, 08:30 AM',
    status: 'AVAILABLE',
    driverId: 'DRV-02',
    driverName: 'Praseed Kumar',
    driverPhone: '+91 98952 77314',
    driverRating: 4.75,
    vehicleNumber: 'KL-58-B-8112',
    isVerifiedDriver: true,
  },
  {
    id: 'LOAD-KN-03',
    supplierId: 'SUP-03',
    supplierName: 'Anthoor Red Stone Quarry',
    supplierPhone: '+91 94460 33811',
    supplierRating: 4.8,
    isVerifiedSupplier: true,
    material: 'Laterite Stone',
    quality: 'Quarry Direct Standard',
    quantity: 600,
    unit: 'stones',
    pickupLocation: 'Anthoor, Kannur',
    pickupCoords: { address: 'Anthoor Quarry, Kannur', lat: 11.9612, lng: 75.3721 },
    destinationLocation: 'Sulthan Bathery, Wayanad',
    destinationCoords: { address: 'Sulthan Bathery Site, Wayanad', lat: 11.6644, lng: 76.2575 },
    materialPrice: 17400,
    transportPrice: 7100,
    platformFee: 500,
    totalPrice: 25000,
    vehicleType: '10-Wheel Heavy Lorry',
    availableDate: 'Day After Tomorrow',
    status: 'AVAILABLE',
    driverName: 'Musthafa K.',
    driverPhone: '+91 94002 11099',
    driverRating: 4.9,
    vehicleNumber: 'KL-13-Z-9901',
    isVerifiedDriver: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'LR1024',
    loadId: 'LOAD-KN-EX-01',
    customerName: 'Anil Varma (Site Owner)',
    customerPhone: '+91 94471 00982',
    deliveryAddress: 'Plot #42, Main Road, Kalpetta, Wayanad',
    pickupCoords: { address: 'Mayyil Quarry, Kannur District', lat: 11.9744, lng: 75.4851 },
    deliveryCoords: { address: 'Plot #42, Main Road, Kalpetta, Wayanad', lat: 11.6094, lng: 76.0827 },
    material: 'Laterite Stone',
    quality: 'Premium Cut Finish (High Strength)',
    quantity: 500,
    unit: 'stones',
    pickupLocation: 'Mayyil Quarry, Kannur',
    deliveryLocation: 'Kalpetta, Wayanad',
    materialPrice: 16500,
    transportPrice: 6500,
    platformFee: 500,
    totalPrice: 23500,
    supplierName: 'Mayyil Laterite Quarry',
    driverId: 'DRV-01',
    driverName: 'Sujith V. (Express Haulers)',
    driverPhone: '+91 94473 88102',
    vehicleNumber: 'KL-13-AF-4921',
    status: 'IN_TRANSIT',
    driverEtaText: '1 hr 35 mins (ETA 04:30 PM)',
    liveDriverLocation: { lat: 11.7850, lng: 75.7820, speedKm: 42 },
    createdAt: 'Today, 08:15 AM',
    deliveryDate: 'Today, 04:30 PM',
  },
];

export const INITIAL_DRIVER_PROFILE: DriverProfile = {
  id: 'DRV-01',
  name: 'Sujith V.',
  phone: '+91 94473 88102',
  vehicleNumber: 'KL-13-AF-4921',
  vehicleType: '10-Wheel Lorry (16 Ton Capacity)',
  rating: 4.88,
  completedTrips: 142,
  isVerified: true,
  isOnline: true,
  todayEarnings: 6500,
  currentLocation: 'Thamarassery / Boys Town Ghat Road (Wayanad bound)',
};

export const INITIAL_SUPPLIER_PROFILE: SupplierProfile = {
  id: 'SUP-01',
  quarryName: 'Mayyil Laterite Quarry Works',
  ownerName: 'P.V. Raghavan',
  phone: '+91 98471 22341',
  location: 'Mayyil, Kannur District, Kerala',
  rating: 4.9,
  isVerified: true,
  activeListingsCount: 4,
  totalSalesCount: 389,
  revenueTotal: 6420000,
};

export const INITIAL_RETURN_LOADS: ReturnLoad[] = [
  {
    id: 'RET-WY-01',
    pickupLocation: 'Kalpetta Crusher Unit, Wayanad',
    destinationLocation: 'Kannur South Bypass Project',
    material: 'Crushed Granite Aggregates (20mm)',
    quantity: '12 Tons',
    earnings: 5400,
    distanceKm: 92,
    status: 'AVAILABLE',
  },
  {
    id: 'RET-WY-02',
    pickupLocation: 'Mananthavady Timber Depot, Wayanad',
    destinationLocation: 'Valapattanam Saw Mill, Kannur',
    material: 'Teak & Hardwood Timber Logs',
    quantity: '10 Tons',
    earnings: 6100,
    distanceKm: 84,
    status: 'AVAILABLE',
  },
];
